version: '3.7'

services:
  api:
    container_name: api
    networks:
      - net
    build: ./sample-api
    ports:
      - 8080:8080

  nginx:
    container_name: nginx
    networks:
      - net
    build: ./nginx/development
    ports:
      - 5000:5000
    depends_on:
      - web

  db:
      container_name: db
      networks:
      - net
      image: mysql/mysql-server:8.0.20
      command: --default-authentication-plugin=mysql_native_password
      ports:
        - ${DATABASE_PORT}:3306
      environment: 
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_ROOT_HOST=%

      expose:
        - ${DATABASE_PORT}
networks:
  net:
      name: net
      driver: bridge